# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 答题

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: [started]
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      DJ_USERNAME: ${{ secrets.DJ_USERNAME }}
      # BBSUSERNAME: ${{ secrets.BBSUSERNAME }}
      # BBSPASSWORD: ${{ secrets.BBSPASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #         run: |
      #           git clone https://github.com/DJ-clamp/myStuffs.git ~/myStuffs
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: add hosts
        if: env.DJ_USERNAME
        run:
          sudo echo "61.178.145.122 www.ygjy.com.cn" | sudo tee -a /etc/hosts
      - name: npm install
        if: env.DJ_USERNAME
        run:
          npm install
      - name: "运行 【学习答题】"
        if: env.DJ_USERNAME
        run:
          #           cd ~/myStuffs
          node Tasks/exam.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
